# Generated by OrbStack.
# This MAY be overwritten in the future. Make a copy and update the include
# in configuration.nix if you want to keep your changes.

{ lib, config, pkgs, ... }:

with lib;

{
  # sudoers
  security.sudo.extraRules= [
    { users = [ "dlbears" ];
      commands = [
        { command = "ALL";
          options= [ "NOPASSWD" ];
        }
      ];
    }
  ];

  # add OrbStack CLI tools to PATH
  environment.shellInit = ''
    . /opt/orbstack-guest/etc/profile-early

    # add your customizations here

    . /opt/orbstack-guest/etc/profile-late
  '';

  # timezone
  time.timeZone = "America/New_York";

  # resolv.conf: NixOS doesn't use systemd-resolved

  # faster DHCP - OrbStack uses SLAAC exclusively
  networking.dhcpcd.extraConfig = ''
    noarp
    noipv6
  '';

  # disable sshd
  services.openssh.enable = false;

  # systemd
  systemd.services."systemd-oomd".serviceConfig.WatchdogSec = 0;
  systemd.services."systemd-userdbd".serviceConfig.WatchdogSec = 0;
  systemd.services."systemd-udevd".serviceConfig.WatchdogSec = 0;
  systemd.services."systemd-timesyncd".serviceConfig.WatchdogSec = 0;
  systemd.services."systemd-timedated".serviceConfig.WatchdogSec = 0;
  systemd.services."systemd-portabled".serviceConfig.WatchdogSec = 0;
  systemd.services."systemd-nspawn@".serviceConfig.WatchdogSec = 0;
  systemd.services."systemd-machined".serviceConfig.WatchdogSec = 0;
  systemd.services."systemd-localed".serviceConfig.WatchdogSec = 0;
  systemd.services."systemd-logind".serviceConfig.WatchdogSec = 0;
  systemd.services."systemd-journald@".serviceConfig.WatchdogSec = 0;
  systemd.services."systemd-journald".serviceConfig.WatchdogSec = 0;
  systemd.services."systemd-journal-remote".serviceConfig.WatchdogSec = 0;
  systemd.services."systemd-journal-upload".serviceConfig.WatchdogSec = 0;
  systemd.services."systemd-importd".serviceConfig.WatchdogSec = 0;
  systemd.services."systemd-hostnamed".serviceConfig.WatchdogSec = 0;
  systemd.services."systemd-homed".serviceConfig.WatchdogSec = 0;

  # ssh config
  programs.ssh.extraConfig = ''
    Include /opt/orbstack-guest/etc/ssh_config
  '';

  # extra certificates
  security.pki.certificates = [
    ''
-----BEGIN CERTIFICATE-----
MIIC5TCCAc2gAwIBAgIJAPlR08J62OrVMA0GCSqGSIb3DQEBCwUAMBQxEjAQBgNV
BAMMCWxvY2FsaG9zdDAeFw0yMjAxMTkwMTA3MjRaFw0yMzAxMTkwMTA3MjRaMBQx
EjAQBgNVBAMMCWxvY2FsaG9zdDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC
ggEBAMeht5wc+F0RWxoc4h6oIZElcap7mlFiICU7BlAqg77+3FQ5QMrBWBsNigk2
LtfRt/v9COxTPUHju9JbISWqSBdSd0U/ropZWWrD3jCsHKtV0GVf6Phvopq7EyHd
IylMejY7uKg5SNlWJe/1NeB+2ARNouPZUEOUDVo13kAynoU1rT4ctZvSuH9My8pS
U9E9LrSZEmrhFTkJ+3shfXOVRd1z+KD4l2l4sh7WsbLs33JBsMemykR33HH9wRnN
qdxpzceAM/x0+bdQOIuiSnegIuuJH3WyKW7vahTxbFRbM1w/1Zr6BzJ8EUs1o/1o
A664vjpyKO7LenUhQ0614eNICXUCAwEAAaM6MDgwFAYDVR0RBA0wC4IJbG9jYWxo
b3N0MAsGA1UdDwQEAwIHgDATBgNVHSUEDDAKBggrBgEFBQcDATANBgkqhkiG9w0B
AQsFAAOCAQEAGxKZvPMFQuPFONBTZs73DYQeB0s1bYM7DyS82n2MsSVkqdn71491
KmZQDxUSsP4nfQfi3wMjlu72QevlbdQvZZrJhI4sUkn/q61e1zLf17f58e8W3tGa
Ccr2OAP1ijg8CwSoBlA55TRE60+eU1V+FAHPLp0vGOm7bz/47imzUsT3vA3VM8+q
1/mFI8gx/3UleA9t45J5A6p/eMp6rogoBkOXf4KoIthFbW2pxRxzytjh8FNZG8pH
j8kuS6gu+KoHzDazd9VkrAZK5aLoDk16DVf5JkzrNZYxbXiXyVFV5bBL35pfjHau
V/JiooY8jWcJ5maNncL3DO632wtqRdSCug==
-----END CERTIFICATE-----

-----BEGIN CERTIFICATE-----
MIIFeTCCBGGgAwIBAgIJAMhKnpPr7bRhMA0GCSqGSIb3DQEBCwUAMIGnMQswCQYD
VQQGEwJVUzETMBEGA1UEBwwKV2lsbWluZ3RvbjEVMBMGA1UECgwMUHJveHltYW4g
TExDMTswOQYDVQQDDDJQcm94eW1hbiBDQSAoMyBKdWwgMjAyMiwgbWFjYm9vay1w
cm8tc3RhYmxlLmxvY2FsKTEcMBoGA1UECwwTaHR0cHM6Ly9wcm94eW1hbi5pbzER
MA8GA1UECAwIRGVsYXdhcmUwHhcNMjIwNzA0MDIyNTMwWhcNMjQxMDA2MDIyNTMw
WjCBpzELMAkGA1UEBhMCVVMxEzARBgNVBAcMCldpbG1pbmd0b24xFTATBgNVBAoM
DFByb3h5bWFuIExMQzE7MDkGA1UEAwwyUHJveHltYW4gQ0EgKDMgSnVsIDIwMjIs
IG1hY2Jvb2stcHJvLXN0YWJsZS5sb2NhbCkxHDAaBgNVBAsME2h0dHBzOi8vcHJv
eHltYW4uaW8xETAPBgNVBAgMCERlbGF3YXJlMIIBIjANBgkqhkiG9w0BAQEFAAOC
AQ8AMIIBCgKCAQEAxlr7vcj8RRayjsN5+c1eEvrZZqnX3XMo/hYej/AwnsDzqjTY
SRDi3LU8UkiSJkVcBEX5w0KHKjJqnHrfCg93EQbRCB7GmddzREBkVGYjOSFEPMGL
1ctR+N2MDkDvyIU19VACEBNfBpX7G4PnASAFFtlyHQaLwGzCcDzDP/pnj0+hnu6W
hunpU3tSNfUxojCcolfOcKZYb5ZJK2RWl2NGW9+CvoDwquaEU8syfVXhLjE5A4Yo
94G+zheZG8LJUPiOiegtM31HDL2xwKfLjc6KInZayW275Fi+6GWs1x2jERVa2RHo
JuC+zUE9uXB3zikLoBAbV62e4DZBXQP/WXfwiwIDAQABo4IBpDCCAaAwHQYDVR0O
BBYEFEqYnR/9PcCTHjvlEt8V9xKGPehOMB8GA1UdIwQYMBaAFEqYnR/9PcCTHjvl
Et8V9xKGPehOMA8GA1UdEwEB/wQFMAMBAf8wDgYDVR0PAQH/BAQDAgIEMIIBHAYJ
YIZIAYb4QgENBIIBDRaCAQlUaGlzIFJvb3QgY2VydGlmaWNhdGUgd2FzIGxvY2Fs
bHkgZ2VuZXJhdGVkIGJ5IFByb3h5bWFuIGZvciBTU0wgUHJveHlpbmcuIElmIHlv
dSBhcmUgYnJvd3NpbmcgYSB3ZWJzaXRlIHRocm91Z2ggUHJveHltYW4gd2l0aCBT
U0wgUHJveHlpbmcgZW5hYmxlZCwgeW91IHdvdWxkIHNlZSB0aGlzIGNlcnRpZmlj
YXRlIGFzIGEgcGFydCBvZiBhIGNlcnRpZmljYXRlIGNoYWluLiBQbGVhc2Ugc2Vl
IGh0dHBzOi8vcHJveHltYW4uaW8gZm9yIG1vcmUgaW5mb3JtYXRpb24uMB0GA1Ud
JQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjANBgkqhkiG9w0BAQsFAAOCAQEABVPn
awOXLxkGeFMAXXyNJ+ZDUGrQs6dQKXHqVx7pP93WLGOleNQsvJ3MP5+CnEIcMyBM
82r+nHTZLppumhKPjxmygUvNA4vYUprRe9pBnBfNI6arvAs8OmOFYtJrMsCSyegf
VlOTu5nZMBDrJET7/eplOmdsxMW7iJd/7r7IdtHC5HafYbAq1BfaY7qjs+zS6pSB
N1TAzoXH6aLQxdpP2ilypEXc6rqFsBXzRBEkHUVLz/4VLxfTtPL4ZjHgaVxFlP+2
3SsumSGAOzIxEnI1wXl8AHkpaatsBUX9XSeGu8sXRRTValmxk4Tw1UueF+EubjvV
c4fRNoW2E5L1Zz6YAQ==
-----END CERTIFICATE-----

-----BEGIN CERTIFICATE-----
MIIDBDCCAeygAwIBAgIRALpX75nHK6VE5Z915hZPMzIwDQYJKoZIhvcNAQELBQAw
KjELMAkGA1UEBhMCRU4xGzAZBgNVBAMMEkFkTG9jayBDVVNUT00gQ0EgMjAgFw0w
MjA2MDgwNzAxMDFaGA8yMDYyMDUyNDA3MDEwMVowKjELMAkGA1UEBhMCRU4xGzAZ
BgNVBAMMEkFkTG9jayBDVVNUT00gQ0EgMjCCASIwDQYJKoZIhvcNAQEBBQADggEP
ADCCAQoCggEBANEC+sWUcfJFToC57ghh7WvGLDrfx5lIp0yrZDEiHXtx32GqAFok
XmwzJ82iDVwIrbDSIf62NBQ5zt5NENdk5oi36rwYlDNWMTEs8rtwGMWJuiZRMale
VPVjL1Ecf2T4cCWiGw83qvNyWDAd4OaYV0DCvBe3YPR7bOKrznwEv/Eycp+NiBOk
pidYnyrdb/A4gsMBuEKYjIQ3z5lrrEuAUrpJADf2jlxTTJ7ede1Dmyga1yzoOeAu
c0ZLEJKaqNG2cwK+tOZ9W7OL/KmHgY/+FhMOd9xzuJoEJnFycjn5x7Ha1+GyScMP
UacT3Z3X9+ukYXyQriyAavLOwwTYdZ4hn+ECAwEAAaMjMCEwDwYDVR0TAQH/BAUw
AwEB/zAOBgNVHQ8BAf8EBAMCAQYwDQYJKoZIhvcNAQELBQADggEBAGz8hHEAtOwl
IfejYPuZBHxGl3yUrwW5ppfIPmuznm5m57LX72Ycb4MlzxH4ro7nK9kO8Zu1FRlB
10VC6wznR3ilsJ3c/eNHGvp9yn0e3CA6JoC5tzfWYD3vUGuFace5oztDNTD8yJpf
dAUQgLHRSd4N569+ABsvTmSBEJhrCEypKXWfPUnHSRBKJai4ASxda/cuyNvKHag0
ez03zb77Wv9lemRChobkw6SajNL4Aphau980RmM6Oq/cs0t2ZGVfZI2ZbED7+Oin
FNkZ0q7fAVFY155aIKnVGx45ODtE3u21MJ+Wreo/EDsjZHA1etEGHGMee7h7RSFy
i3nErm9HDz8=
-----END CERTIFICATE-----

-----BEGIN CERTIFICATE-----
MIIFGDCCA4CgAwIBAgIRAKzv+4KMFg3sVOMkwz6j1jUwDQYJKoZIhvcNAQELBQAw
gaMxHjAcBgNVBAoTFW1rY2VydCBkZXZlbG9wbWVudCBDQTE8MDoGA1UECwwzZGxi
ZWFyc0BNQlAtc3RhYmxlLmZpb3Mtcm91dGVyLmhvbWUgKERlbm5pcyBPcnNpbmkp
MUMwQQYDVQQDDDpta2NlcnQgZGxiZWFyc0BNQlAtc3RhYmxlLmZpb3Mtcm91dGVy
LmhvbWUgKERlbm5pcyBPcnNpbmkpMB4XDTI0MDIxNDAzMzQzMloXDTM0MDIxNDAz
MzQzMlowgaMxHjAcBgNVBAoTFW1rY2VydCBkZXZlbG9wbWVudCBDQTE8MDoGA1UE
CwwzZGxiZWFyc0BNQlAtc3RhYmxlLmZpb3Mtcm91dGVyLmhvbWUgKERlbm5pcyBP
cnNpbmkpMUMwQQYDVQQDDDpta2NlcnQgZGxiZWFyc0BNQlAtc3RhYmxlLmZpb3Mt
cm91dGVyLmhvbWUgKERlbm5pcyBPcnNpbmkpMIIBojANBgkqhkiG9w0BAQEFAAOC
AY8AMIIBigKCAYEA0Ece8dXS0l1RvulugKJgXaL3zUqQ1PKVe3eVCelPn5h4luYp
8BFemlHawrd58dZvUe+JG+VXOAcC7CTzvrhcdmpsaLT+m/B03Bo/5NdRM0rmjIlc
sMrPX4d/M1LydryMELYGQ5gHkKwQXudkM/9RYwBKguahdn2EgaQcaZtqOBKrOu74
G5L6WBDVlIdlJOh2XTmHr/7rRwSM21eM/k/qBqK8D+4AQ9wTlp7AJofjblyef7Hh
+WbzAkmXfiZMoXeYuusCUElwVyxpy+tsl6bawjCbP1acqzyq9kr6fx8Dgf3vg9bG
oT/AW0sy05ls2K7BzFj8kn8kGTUZ0+8z5SSIsipQnw/PqA6VQp0BGlNH5d6U9K4Y
9FaVUrevELI575YRkyxfrYLDOFts4y5W/1ztgnRZbp4HnymHJSEHUXSdMxK1eyXk
14/1M79g6sfMDdYcpSYXEEkYow14KL2SuqcoRPjT2meQL8id30SJhBU9bIynlitp
6+vePp2pADSw3zpBAgMBAAGjRTBDMA4GA1UdDwEB/wQEAwICBDASBgNVHRMBAf8E
CDAGAQH/AgEAMB0GA1UdDgQWBBTjsHyjbWmErhIQGDiLeojp4P32gjANBgkqhkiG
9w0BAQsFAAOCAYEAiYaIyj51ivH5SKFwM1MWHcM+Bj+SutcPT5JhEV7/G6c9vzIO
lLm0kE5hqYYJ8iFv31Q4Rxpdo1E+Iv3Y9tHsvmuEQCtKUg74kM5FwUPeSC8t2qMl
PnebruShn4hMwcED+bPKC3MVE9qfr+2tCHNocxvMEU4Y8Nu2aPWLeLQ+ZHU2wABD
xAnz0cl4SSt1b9wQ7xX0ILYKPaO793qKRSFYnkJ3W/CMPHByK1DspeElhCsTWhpk
9fht6akbANh2KigqsUh1Ml5qroJ49/q817UQvMxdMRiUIkii1fiH7Qtcx4sSuNsS
aPfjQBJZZWAE5uyKZxghPT2W8GFyOHYHf4pHW+0D4zy5FgSyme2iICENq1rDTCMi
GPa+FcqiLaGhqkScg/ZwNLHmXjCtWT+FDE5i2i8Pv9klqOhD9rbo04gf+gHwV0E1
uQongFSdgAzqGTYFtaagTAPCgd6RIVTfJfZ+Vcc5xTQJwQkWKJ3tNxsagOalTdMS
l7TrI+0aXh30kCk+
-----END CERTIFICATE-----

-----BEGIN CERTIFICATE-----
MIIFLjCCAxagAwIBAgIQalXDHRVvw+d6lDC8u80XMTANBgkqhkiG9w0BAQsFADAx
MRUwEwYDVQQKEwxOZXh0RE5TIEluYy4xGDAWBgNVBAMTD05leHRETlMgUm9vdCBD
QTAeFw0yMDAxMDEwMDAwMDBaFw00MDAxMDEwMDAwMDBaMDExFTATBgNVBAoTDE5l
eHRETlMgSW5jLjEYMBYGA1UEAxMPTmV4dEROUyBSb290IENBMIICIjANBgkqhkiG
9w0BAQEFAAOCAg8AMIICCgKCAgEA/XxolBTLZlK7723ufhb39RHo8e4IiXohvVtT
ucUxEhHKzxhnexKMOHDbFoBniGOuepFoIbHAP86pERXUQ2GatNftAnCZp+WAIlmo
HRgwVM93AhEus54YIrZa5MZJdu1BLWxanRzCzCLy+j3a6Lda3fpMsIrB2DFI1uup
fRre4FCXGiEjJ7Sg0pstecH+7RYGr5lFhsl1n7RZQ1qKOk0jY3h6UtGyujodz9PX
HtG6AA3GpAlNOAseIHwhzwVhYJlVysG8oLOy2wq4GEnomU/l/9B1SC24815LAV+u
yGLcyYdXO3QnK0borz46hGg532HCVXZ8I3azioaVs+z5GiFKa7tPH3s2Y4do846i
1Hr8aTXrCCcGKguDqHblRsA+lsp7qZldbBmx65UJjTv3qm4AH2ktAX4Oqz/hH92f
qkol+CWgtkxTNbOSv9Ypu+wRkRFCiiK6wBj1fQulkZy2E03RYuGywx53312L0mPR
gRpDl6K4nkXZ+IfkJKxVvHTg6kD9yXy8H7zBNfLYVhODydFpSZANj7qE/UQ7sWnR
BoX3EEA2Sz9X64LfCNSMe39gxjR2l9tsy84LIwimyEWF5wh+amlpS0NUJqHV4a7D
aymBhFL6LdruDXhuoK72rUalVDA0xIrYPA5QA6o9xZpN3shfB2fbQffkybF+WCeU
EHdE1skCAwEAAaNCMEAwDgYDVR0PAQH/BAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8w
HQYDVR0OBBYEFHX0wb8dexh2ldvQgETQerb8fQCvMA0GCSqGSIb3DQEBCwUAA4IC
AQBIbfu2TLg+CssHmc70EA4qYlV1jhsJeIgzqlq0TfhIlupUsAD/KQHnm1bHqexM
QaABCAdy1u59MVeYIxXQI4bIaQqZXTnvgPdB/9FAzMIO0DZEzXLPVsoWq/jnSUHd
v3RKttJke002CmfyjXS+mVjVYAwgCs/Plidwf5jGH6tYc3L/UvNIoq4DSoCe0/w8
1209TB5ijWfxiL7JbX+J0HnvxPRK1Esv8hzwaPxbaAFSOlDnWAazMl+28AhfA1qk
ZybQIvJg/VjYzLCBoDLwb1TpYehO8dFU3cKWjwqKmSN6siKdHLQWpzoembyFwaJF
5frcWeNUd4i82yRykZMErvURYRv66jQSiF7m6SE5Uzxmonxv6srb6Fe0jNSPzjnr
aFTDGaKl8fBtrSS17++HUbr+PTetQTXrZE5eMoSszZTnnRPBoNLtdOuaw0TPcawb
OieeSgK9VuOn/fLqRDpY8c6K2gyz2MUq2G5J93ZWpbjMAd5f4YYHIlCpkpqhCBhK
9+o7vk/seHd8F1YrsOLlmCgQ1n5uIddHWkYOhBYN/Y8gr6x1jjBGPQnD81DntVLY
1P0f4iAn43RAOPRLJ1/Q1eUlZcbd1vJ6TBcDvDOfOJV6sY6mcu1Uj0gIlzm2Y8Ui
i4ZPXRpyFidVsWxF2skF71ZPVwXU/+SMTJafHvKY9KU8kA==
-----END CERTIFICATE-----

    ''
  ];

  # indicate builder support for emulated architectures
  nix.extraOptions = "extra-platforms = x86_64-linux i686-linux";
}
